Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/11/2022
Var
i : inteiro


Inicio
 i <- 0
 
 enquanto i<=100 faca

          escreval(i)
          i<- i+1
          se i =50 entao
             escreval( "o i vale 50")
             interrompa
          fimse
fimenquanto
          escreval(*******FIM DO PROGRAMA********)
Fimalgoritmo